<a href="https://colab.research.google.com/github/albasr06/TFM-Matrices-Python/blob/main/Actividad_2_Manipulando_y_Operando_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Define un ejemplo de matriz identidad, diagonal, triangular superior e inferior, y rectangular. (1 pto)

In [ ]:

import numpy as np
# Definición de las matrices
identidad = np.identity(5)
diagonal = np.diag([1, 2, 3, 4])
triangular_superior = np.array([[5, 6, 7, 0], [0, 8, 9, 0], [0, 0, 10, 11], [0, 0, 0, 12]])
triangular_inferior = np.array([[5, 0, 0, 0], [6, 7, 0, 0], [8, 9, 10, 0], [11, 12, 13, 14]])
rectangular = np.array([[1, 2, 3], [4, 5, 6]])

Investiga en la documentación de numpy acerca de la función array_equal. Usala para hacer un código que me diga si una matriz es rectangular o cuadrada, y detecte si es diagonal, triangular o simétrica. Usa las matrices que definistes arriba para comprobar que funciona correctamente. (3 ptos)

In [4]:


# Función para clasificar las matrices
def clasificar_matriz(matriz):
    print('La matriz \n',matriz, 'es:')
    if matriz.shape[0] != matriz.shape[1]:
        print("Rectangular")
    else:
        print("Cuadrada")

        if np.array_equal(matriz, np.diag(np.diagonal(matriz))):
            print("Diagonal")
        elif np.array_equal(matriz, np.triu(matriz)):
            print("Triangular superior")
        elif np.array_equal(matriz, np.tril(matriz)):
            print("Triangular inferior")
        elif np.array_equal(matriz, matriz.T):
            print("Simétrica")
        else:
            print("Otra")

clasificar_matriz(identidad)
clasificar_matriz(diagonal)
clasificar_matriz(triangular_superior)
clasificar_matriz(triangular_inferior)
clasificar_matriz(rectangular)


La matriz 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] es:
Cuadrada
Diagonal
La matriz 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]] es:
Cuadrada
Diagonal
La matriz 
 [[ 5  6  7  0]
 [ 0  8  9  0]
 [ 0  0 10 11]
 [ 0  0  0 12]] es:
Cuadrada
Triangular superior
La matriz 
 [[ 5  0  0  0]
 [ 6  7  0  0]
 [ 8  9 10  0]
 [11 12 13 14]] es:
Cuadrada
Triangular inferior
La matriz 
 [[1 2 3]
 [4 5 6]] es:
Rectangular


Busca la definición de traza de una matriz, y define una función que la calcule.(2 ptos)

In [5]:


def calcular_traza(matriz):
  """Calcula la traza de una matriz"""
  if matriz.shape[0] != matriz.shape[1]:
    return 0  # O cualquier otro valor que indique que no se puede calcular la traza
  traza = 0
  for i in range(matriz.shape[0]):
    traza += matriz[i, i]
  return traza

# Ejemplo de uso:
matriz_ejemplo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
traza = calcular_traza(matriz_ejemplo)
print("La traza de la matriz es:", traza)

La traza de la matriz es: 15


Por lo general, el producto de matrices no es conmutativo. Crea una función en Python que compruebe, para dos matrices A y B, si se pueden multiplicar, y si es asi, si el producto es conmutativo o no. (4 ptos)



In [6]:


def producto_y_conmutatividad(A, B):
  """
  Calcula el producto de A por B y B por A, si es posible, y comprueba si el producto es conmutativo.

  Retorna:
    Una tupla que contiene:
      - El producto de A por B, si es posible, o None si no lo es.
      - El producto de B por A, si es posible, o None si no lo es.
      - True si el producto es conmutativo y las matrices se pueden multiplicar, False si no lo es, o None si no se pueden multiplicar.
  """
  if A.shape[1] == B.shape[0]:
    AB = np.dot(A, B)
  else:
    AB = None

  if B.shape[1] == A.shape[0]:
    BA = np.dot(B, A)
  else:
    BA = None

  if AB is not None and BA is not None:
    if np.array_equal(AB, BA):
      return AB, BA, True
    else:
      return AB, BA, False
  else:
    return AB, BA, None


# Ejemplo de matrices no conmutativas
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

AB, BA, conmutativo = producto_y_conmutatividad(A, B)

if AB is not None and BA is not None:
  print("A x B = \n", AB)
  print("B x A = \n", BA)
  if conmutativo:
    print("El producto es conmutativo.")
  else:
    print("El producto no es conmutativo.")
else:
  print("No se pueden multiplicar las matrices.")


# Ejemplo de matrices conmutativas
A = np.array([[1, 0], [0, 1]])  # Matriz identidad
B = np.array([[2, 0], [0, 2]])  # Matriz diagonal

AB, BA, conmutativo = producto_y_conmutatividad(A, B)

if AB is not None and BA is not None:
  print("\nA x B = \n", AB)
  print("B x A = \n", BA)
  if conmutativo:
    print("El producto es conmutativo.")
  else:
    print("El producto no es conmutativo.")
else:
  print("No se pueden multiplicar las matrices.")

A x B = 
 [[19 22]
 [43 50]]
B x A = 
 [[23 34]
 [31 46]]
El producto no es conmutativo.

A x B = 
 [[2 0]
 [0 2]]
B x A = 
 [[2 0]
 [0 2]]
El producto es conmutativo.
