<a href="https://colab.research.google.com/github/albasr06/TFM-Matrices-Python/blob/main/Apuntes_definicion_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Asignaturas: Matemáticas, Ciencias, Inglés
calificaciones = [
    [6.5, 8.2, 4.9],  # Ana
    [9.1, 5.7, 6.3],  # Luis
    [7.4, 3.5, 9.8],  # María
    [2.3, 9.0, 7.1]   # Carlos
]
print(calificaciones)

[[6.5, 8.2, 4.9], [9.1, 5.7, 6.3], [7.4, 3.5, 9.8], [2.3, 9.0, 7.1]]


In [ ]:

n_filas = len(calificaciones)
n_columnas = len(calificaciones[0])
print( 'Hay', n_filas, 'alumnos y', n_columnas, 'asignaturas ')


Hay 4 alumnos y 3 asignaturas 


In [ ]:
nota_ana_mates = calificaciones[0][0]
print('La nota de Ana en Matemáticas es un', nota_ana_mates)

La nota de Ana en Matemáticas es un 6.5


In [ ]:
calificaciones[0][0] += 1
print('La nueva nota de Ana en Matemáticas es un', calificaciones[0][0])

La nueva nota de Ana en Matemáticas es un 7.5


In [ ]:
def imprimir_matriz(matriz):
    n_filas = len(matriz)
    n_columnas = len(matriz[0])

    # Recorrer cada fila de la matriz
    for i in range(n_filas):
        # Recorrer cada columna de la fila actual
        for j in range(n_columnas):
            # Imprimir la posición y el valor del elemento actual
            print(f"El valor en la posicion [{i}][{j}] es ",matriz[i][j])

imprimir_matriz(calificaciones)

El valor en la posicion [0][0] es  7.5
El valor en la posicion [0][1] es  8.2
El valor en la posicion [0][2] es  4.9
El valor en la posicion [1][0] es  9.1
El valor en la posicion [1][1] es  5.7
El valor en la posicion [1][2] es  6.3
El valor en la posicion [2][0] es  7.4
El valor en la posicion [2][1] es  3.5
El valor en la posicion [2][2] es  9.8
El valor en la posicion [3][0] es  2.3
El valor en la posicion [3][1] es  9.0
El valor en la posicion [3][2] es  7.1


In [ ]:
#Creamos una lista donde guardar las notas de Luis
#(segunda fila)
notas_luis = calificaciones[1]

# Calculamos la media de las calificaciones de Luis
media_luis = sum(notas_luis) / len(notas_luis)

# Mostramos la media
print(media_luis)

7.033333333333334


In [ ]:
#Creamos una lista vacía donde almacenar las notas
notas_matematicas = []
# Extraemos las calificaciones de Matemáticas (primera columna)
for fila in calificaciones:
    notas_matematicas.append(fila[0])

# Calculamos la media de las calificaciones de Matemáticas
media_matematicas = sum(notas_matematicas) / len(notas_matematicas)

# Mostramos la media
print(media_matematicas)

6.575


In [ ]:
#La primera vez que utilizamos numpy es necesario instalar la librería
!pip install numpy
#importamos la librería
import numpy as np
calificaciones_numpy = np.matrix(calificaciones)
print("Matriz de calificaciones usando NumPy:")
print(calificaciones_numpy)

Matriz de calificaciones usando NumPy:
[[7.5 8.2 4.9]
 [9.1 5.7 6.3]
 [7.4 3.5 9.8]
 [2.3 9.  7.1]]


In [ ]:
print(type(calificaciones))
print(type(calificaciones_numpy))

<class 'list'>
<class 'numpy.matrix'>


In [ ]:
dimension_calificaciones = calificaciones_numpy.shape
print('La dimensión de esta matriz es', dimension_calificaciones[0], 'x', dimension_calificaciones[1])

La dimensión de esta matriz es 4 x 3


In [ ]:
#Notas de Ana
print(calificaciones_numpy[0])
#Notas en Matemáticas
print(calificaciones_numpy[:,0])

#Nota de Ana en Matemáticas
print(calificaciones_numpy[0,0])


[[7.5 8.2 4.9]]
[[7.5]
 [9.1]
 [7.4]
 [2.3]]
7.5


In [ ]:
media_matematicas = calificaciones_numpy[:,0].mean()
print(media_matematicas)
media_luis = calificaciones_numpy[1].mean()
print(media_luis)

6.575
7.033333333333334


In [ ]:
#media por columnas
medias_asignaturas = calificaciones_numpy.mean(axis=0)
print(medias_asignaturas)

#media por filas
medias_alumno = calificaciones_numpy.mean(axis=1)
print(medias_alumno)

#media de todos los valores
media_total = calificaciones_numpy.mean()
print(media_total)

[[6.575 6.6   7.025]]
[[6.86666667]
 [7.03333333]
 [6.9       ]
 [6.13333333]]
6.733333333333332
