<a href="https://colab.research.google.com/github/albasr06/TFM-Matrices-Python/blob/main/Apuntes_tipos_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

# Matriz cuadrada
matriz_cuadrada = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
print("Matriz cuadrada:")
print(matriz_cuadrada)
print("Dimensión:", matriz_cuadrada.shape)


# Matriz rectangular
matriz_rectangular = np.array([[1, 2, 3],
                              [4, 5, 6]])
print("\nMatriz rectangular:")
print(matriz_rectangular)
print("Dimensión:", matriz_rectangular.shape)


# Matriz fila
matriz_fila = np.array([[1, 2, 3]])
print("\nMatriz fila:")
print(matriz_fila)
print("Dimensión:", matriz_fila.shape)


# Matriz columna
matriz_columna = np.array([[1],
                           [2],
                           [3]])
print("\nMatriz columna:")
print(matriz_columna)
print("Dimensión:", matriz_columna.shape)

Matriz cuadrada:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensión: (3, 3)

Matriz rectangular:
[[1 2 3]
 [4 5 6]]
Dimensión: (2, 3)

Matriz fila:
[[1 2 3]]
Dimensión: (1, 3)

Matriz columna:
[[1]
 [2]
 [3]]
Dimensión: (3, 1)


In [ ]:

#diagonal principal
print(matriz_cuadrada.diagonal())

#diagonal secundaria
matriz_cuadrada_flip = np.fliplr(matriz_cuadrada)
print(matriz_cuadrada_flip)
print(matriz_cuadrada_flip.diagonal())

##elementos en la diagonal superior a la principal
print(matriz_cuadrada.diagonal(offset=1))

##elementos en la diagonal inferior a la principal
print(matriz_cuadrada.diagonal(offset=-1))


<class 'numpy.matrix'>
[[1 5 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 5 7]]
[[2 6]]
[[4 8]]


In [ ]:
#matriz triangular
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#triangular superior
print(np.triu(matriz_cuadrada))
#triangular inferior
print(np.tril(matriz_cuadrada))

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
#matriz nula
np.zeros((2, 3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#matriz transpuesta
a = np.array([[1, 2, 3], [4,0,3]])
print(np.transpose(a))

[[1 4]
 [2 0]
 [3 3]]
