<a href="https://colab.research.google.com/github/albasr06/TFM-Matrices-Python/blob/main/Apuntes_Operaciones_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Definir las matrices A y B usando numpy.matrix
A = np.matrix([
    [25, 27, 26],
    [24, 26, 25],
    [23, 24, 23],
    [22, 23, 22]
])

B = np.matrix([
    [28, 30, 29],
    [27, 29, 28],
    [26, 28, 27],
    [25, 27, 26]
])

# Sumar las matrices A y B
suma_matrices = A + B
print(suma_matrices)


[[53 57 55]
 [51 55 53]
 [49 52 50]
 [47 50 48]]


In [ ]:
resta_matrices = A - B
print(resta_matrices)

[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -4 -4]
 [-3 -4 -4]]


In [ ]:
2*A

matrix([[50, 54, 52],
        [48, 52, 50],
        [46, 48, 46],
        [44, 46, 44]])

In [ ]:
ventas = np.matrix([
    [150, 200, 100],
    [80, 120, 90],
])
precios = np.matrix([[20],[30],[50]])
ingresos = np.dot(ventas,precios)
print(ingresos)

[[14000]
 [ 9700]]
